name: CI

# Trigger the workflow on push or pull request (for all branches)
on: [push]

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  Movymporter:
    runs-on: ubuntu-latest

    # Initialization
    steps:
      - name: Set up environment, retrieving the repository
        uses: actions/checkout@main
      - name: where am I?
        run: pwd && ls -la
      - name: Initialize Docker images
        run: bin/initialize
      - name: Create .env file
        run: |
          echo "LOG_LEVEL=INFO" > .env
          echo "CSV_IN=tester.csv" >> .env
          echo "URL_OUT=http://localhost:9009/movies" >> .env
          echo "STOP_ON_ERRORS=1" >> .env
      - name: Install python modules
        run: python3 -m pip install --requirement requirements.txt
      - name: Run code
        run: python3 movymporter
